//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KahveMVC.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class iletisimformu
    {
        public int id { get; set; }
        public string adSoyad { get; set; }
        public string eposta { get; set; }
        public string mesaj { get; set; }
        public bool cinsiyet { get; set; }
        public bool izin { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
    }
}
