//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KahveMVC.Models.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MobilyaDbEntities : DbContext
    {
        public MobilyaDbEntities()
            : base("name=MobilyaDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<anasayfa> anasayfa { get; set; }
        public DbSet<hakkimizda> hakkimizda { get; set; }
        public DbSet<iletisimformu> iletisimformu { get; set; }
        public DbSet<kullanici> kullanici { get; set; }
        public DbSet<magaza> magaza { get; set; }
        public DbSet<magazasaat> magazasaat { get; set; }
        public DbSet<urunler> urunler { get; set; }
        public DbSet<siparis> siparis { get; set; }
        public DbSet<siparisdetay> siparisdetay { get; set; }
    }
}
