//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KahveMVC.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class siparisdetay
    {
        public int id { get; set; }
        public int siparisId { get; set; }
        public Nullable<int> urunId { get; set; }
        public Nullable<decimal> fiyat { get; set; }
        public Nullable<int> adet { get; set; }
    
        public virtual siparis siparis { get; set; }
        public virtual urunler urunler { get; set; }
    }
}
