//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KahveMVC.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class siparis
    {
        public siparis()
        {
            this.siparisdetay = new HashSet<siparisdetay>();
        }
    
        public int id { get; set; }
        public string adSoyad { get; set; }
        public string telefon { get; set; }
        public string adres { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
        public Nullable<decimal> toplamTutar { get; set; }
        public string durum { get; set; }
        public Nullable<int> kullaniciId { get; set; }
    
        public virtual ICollection<siparisdetay> siparisdetay { get; set; }
    }
}
