//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KahveMVC.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class urunler
    {
        public urunler()
        {
            this.siparisdetay = new HashSet<siparisdetay>();
        }
    
        public int id { get; set; }
        public string baslik { get; set; }
        public string ustBaslik { get; set; }
        public string icerik { get; set; }
        public string foto { get; set; }
        public Nullable<int> Fiyat { get; set; }
        public int sira { get; set; }
        public bool aktif { get; set; }
        public Nullable<int> stok { get; set; }
    
        public virtual ICollection<siparisdetay> siparisdetay { get; set; }
    }
}
